# -*- coding: utf-8 -*-
"""Convert string to list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqxyVBu_TKchmElIKdVuwsOkIWC7aoIO
"""

def convert_string(string):
    lst = []
    for item in string:
        lst.append(int(item))  # Convert each character to an integer
    return lst

arr = "45678"
result = convert_string(arr)
print(result)