# -*- coding: utf-8 -*-
"""convert comma separated elements to list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqxyVBu_TKchmElIKdVuwsOkIWC7aoIO
"""

elements= input("Enter comma separated elements:")
elements_list= elements.split(',')
elements_list = [element.strip() for element in elements_list]

# Print the resulting list
print("The list is:", elements_list)